config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }, path_names: {
    sign_in: 'log_in',
    sign_up: 'create_account',
    sign_out: 'logout'
  }

  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
#   has_many :created_posts, class_name: 'Post', foreign_key: :author_id
#   has_many :comments, foreign_key: :author_id, class_name: 'Comment'
#   has_many :posts, through: :comments
#   has_many :likes, foreign_key: :author_id, class_name: 'Like'
#   has_many :posts, through: :likes
# end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  validates :name, presence: true
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal: 0

  # These gets only all the posts created by a specific user
  has_many :created_posts, class_name: 'Post', dependent: :destroy
  # these gets all the comments made by a specific user
  has_many :comments, dependent: :destroy
  # these gets all the posts created by a specifc user that has been commented on
  has_many :commented_posts, through: :comments, source: :user, class_name: 'Comment'
  # these gets all the likes of a specific user
  has_many :likes, class_name: 'Like', dependent: :destroy
  # these gets all the posts liked by a specifc user
  has_many :posts, through: :likes

  # These gets all the recent psots of a user
  scope :top_three_posts_of_user, ->(id, total) { find(id).created_posts.order('created_at DESC').limit(total) }

  before_validation :trim_text

  # class method to get top three posts a given user
  def self.top_three_posts(args)
    User.find_by(args).created_posts.order('created_at DESC').limit(3)
  end

  # instance method to get top three posts for a given user
  def top_three_posts(limit = 3)
    created_posts.order(created_at: :desc).limit(limit)
  end

  def trim_text
    name.strip! if name.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.top_three_posts
  end
end

app/views/users/_user_card.html.erb
<div class="profile mb-2">
  <div class="profile__picture">
    <%= image_tag 'https://i.pravatar.cc/150?img=2', alt: "profile" %>
  </div>
  <div class="profile__details">
    <h6 class="profile__details-name"><%= user.name.capitalize %></h6>
    <div class="posts_counter"><%= t("post.total", count: user.posts_counter) %></div>
  </div>
</div>

app/views/users/_user_list.html.erb
<li class="profile__item">
  <%= render partial: "user_card", locals: { user: { name: "user #{no}", posts: no } } %>
</li>

app/views/users/index.html.erb
<div class="profile__container">
  <ul class="profile__list">
    <% @users.each do |u| %>
      <li class="profile__item">
        <%= link_to user_path(u.id) do %>
          <%= render partial: "user_card", locals: { user: u } %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="profile__container">
  <%= render partial: "user_card", locals: { user: @user } %>
  <div class="bio">
    <h5 class="bio__heading">Bio</h5>
    <p class="bio__text"><%= @user.bio %> </p>
  </div>
  <ul class="post__list">
    <% @posts.each do |p| %>
      <li class="post__item">
        <%= render partial: "posts/post_card", locals: { post: p } %>
      </li>
    <% end %>
  </ul>
  <div class="actions">
    <%= link_to "See all posts", user_posts_path(@user.id), class: "btn" %>
  <div>
</div>