config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }, path_names: {
    sign_in: 'log_in',
    sign_up: 'create_account',
    sign_out: 'logout'
  }

  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# class Post < ApplicationRecord
#   belongs_to :creator, foreign_key: :author_id, class_name: 'User'
#   has_many :comments
#   has_many :users, through: :comments, source: :author, foreign_key: :author_id
#   has_many :likes
#   has_many :users, through: :likes, source: :author, foreign_key: :author_id
# end

class Post < ApplicationRecord
  validates :title, presence: { message: 'Title must not be blank' },
                    length: { maximum: 250, too_long: 'Title must not exceed 250 characters' }
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal: 0

  # these gets user that created a specific post
  belongs_to :user, counter_cache: :posts_counter
  # these gets all the comments made on a specific post
  has_many :comments, dependent: :destroy
  # these gets all the users that made comments on a specific post
  has_many :user_comments, through: :comments, source: :post, class_name: 'Comment'
  # these gets all the likes for a specific post
  has_many :likes, dependent: :destroy
  # these gets all the users that liked a specific post
  has_many :users, through: :likes
  # enforce presence of user on specific post creation
  validates_associated :user
  # select all post other than the first post
  scope :not_id_of_one, -> { where('id != 1') }
  # get all posts and order by created_at
  scope :by_creation, ->(post_id) { where('id = ?', post_id).order('created_at DESC') }

  before_validation :trim_text

  def self.update_post_counter(id)
    post = Post.find(id)
    user = post.user
    user.update_column('posts_counter', user.posts_counter + 1)
  end

  def update_post_counter
    user.update_column('posts_counter', user.posts_counter + 1)
  end

  # class method to get top 5 comments for a given post
  def self.five_most_recent_comments(post_id)
    post = Post.find(post_id)
    post.comments.order('created_at DESC').limit(5)
  end

  # instance method to get top 5 comments for a given post
  def five_most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def trim_text
    title.strip! if title.present?
    text.strip! if text.present?
  end

  # auto update comments_counter for existing post
  # def self.update_comments_counter(post_id)
  #   post = Post.find(post_id)
  #   total_comments = post.comments.size
  #   post.update_column('comments_counter', total_comments)
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.top_three_posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    new_post = Post.new(post_params)
    current_user.created_posts << new_post
    if new_post.save
      flash[:notice] = 'Post created!'
      redirect_to user_posts_path(new_post.user.id)
    else
      flash.now[:alert] = 'Failed to create post!'
      render :new
    end
  end

  def destroy
    post_to_delete = Post.find(params[:id])
    owner = post_to_delete.user
    if post_to_delete.destroy
      flash[:notice] = 'Post destroyed successfully!'
    else
      flash[:alert] = 'Unable to delete post'
    end
    redirect_to user_posts_path(owner.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_comment_card.html.erb
<ul class="comment__list">
  <% comments_with_user(comments).each do |c| %>
    <li class="comment__item">
      <span class="comment__item-user"><%= c.user.name  %>:  </span>
      <span class="comment__item-comment"><%= c.text %> </span>
      <div class="trash__container">
        <% if can? :destroy, c %>
          <%= button_to comment_path(c.id), method: :delete, class: "trash-btn" do %>
            <i class='bx bx-trash-alt box-icon'></i>
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/_comment_form.html.erb
<div class="form__container">
  <%= form_with url: post_comments_path(post.id), scope: :data do |f| %>
    <div class="field">
      <%= f.text_area :text, size: "60x10", required: true, placeholder: "Write comment...", class: "text_area" %>
    </div>
    <div class="actions">
      <%= f.submit "Comment", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/posts/_like_view.html.erb
<% if post_liked_by?({ post: post, id: current_user.id }) %>
  <b class= "liked">Liked by you</b>
<% else %>
  <%= form_with url: post_likes_path(post.id) do |form| %>
    <%= form.submit "Like", class: "like btn" %>
  <% end %>
<% end %>

app/views/posts/_no_of_comments.html.erb
<span><%= t("post.comments", count: total_comments) %> </span>

app/views/posts/_no_of_likes.html.erb
<span> <%= t("post.likes", count: total_likes) %> </span>

app/views/posts/_post_card.html.erb
<div class="post mb-2 mt-2">
  <div class="post__header">
    <%= link_to user_post_path(@user.id, post.id) do %>
      <h5 class="post__title"><%= capitalize(post.title) %></h5>
    <% end %>
    <% if can? :destroy, post %>
      <%= button_to post_path(post.id), method: :delete, class: "trash-btn" do %>
        <i class='bx bx-trash-alt box-icon'></i>
      <% end %>
    <% end %>
  </div>
  <p class="post__text"><%= shorten_text(post.text) %>  </p>
  <div class="post__likes_comments_counter">
    <%= render partial: "posts/no_of_comments", locals: { total_comments: post.comments_counter } %>, <%= render partial: "posts/no_of_likes", locals: { total_likes: post.likes_counter } %>
  </div>
</div>

app/views/posts/_post_with_comment_card.html.erb
<li class="post__comment-item mb-2">
   <%= render partial: "post_card", locals: { post: post } %>
  <% if can_display_comments?(post.comments_counter) %>
    <%= render partial: "comment_card", locals: { comments: post.five_most_recent_comments } %>
  <% end %>
</li>

app/views/posts/index.html.erb
<div class="profile__container">
  <%= render partial: "users/user_card", locals: { user: @user } %>
    <ul class="post__comment">
      <% @posts.each do |p| %>
        <%= render partial: "post_with_comment_card", locals: { post: p } %>
      <% end %>
    </ul>
  <button class="btn">Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="form__container">
  <%= form_with url: posts_path, model: @post do |f| %>
    <h6 class="form__header">Create new post</h6>
    <div class="field">
      <%= f.text_field :title, class: "input", required: true, placeholder: "Title", value: nil %>
    </div>
    <div class="field">
      <%= f.text_area :text, size: "60x10", required: true, placeholder: "Write text here...", value: nil, class: "text_area" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="profile__container">
  <div class="post">
    <div class="header">
      <%= link_to user_posts_path(@user.id) do %>
        <h5 class="post__title"><%= capitalize(@post.title) %> by <%= capitalize(@user.name) %></h5>
      <% end %>
      <div class="post__likes_comments_counter">
        <%= render partial: "posts/no_of_comments", locals: { total_comments: @post.comments_counter } %>, <%= render partial: "posts/no_of_likes", locals: { total_likes: @post.likes_counter } %>
      </div>
    </div>
    <div class="like__container">
      <% if can? :destroy, @post %>
        <%= button_to post_path(@post.id), method: :delete, class: "trash-btn" do %>
          <i class='bx bx-trash-alt box-icon'></i>
        <% end %>
      <% end %>
      <%= render partial: "like_view", locals: { post: @post } %>
    </div>
    <p class="post__text"><%= @post.text %> </p>
  </div>
  <% if can_display_comments?(@post.comments_counter) %>
    <%= render partial: "comment_card", locals: { comments: @post.comments } %>
  <% end %>
  <%= render partial: "comment_form", locals: { post: @post } %>

</div>